# -*- coding: utf-8 -*-
"""Website_Screenshot_Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12CNxnyEFX-Xn-9wy6w0E-aeIVzGBhddB
"""

from selenium import webdriver
import pandas as pd 
import urllib.request
import os
 
  
def readCsv():
  data = pd.read_csv("C:/Users/Philipp.Meier/Nextcloud/DeeptechAI/data/urls.csv", sep = ";", encoding = "ISO-8859-1")
  return data

def getListOfURLs(csvData):
  urlList = list()
  for url in csvData.Domain:
    urlList.append(url)
  return urlList

def capture():

    options = Options()
    options.add_argument('-headless')
    driver = webdriver.Firefox(executable_path = 'C:\\Users\\Philipp.Meier\\Nextcloud\\geckodriver.exe', options=options)

    urlList = getListOfURLs(readCsv())
    for i in range(0, len(urlList)):
      url = urlList[i]
      print("TRYING: " + str(i))
      try:
        driver.get('https://' + url)
      except urllib.error.URLError as e:
        print("# URLError: Switching to http")
        try: 
          driver.get('http://' + url)
        except Exception as e:
          print("HTTP and HTTPS call not possible, skipping website..." + url + str(e))
          continue
      except Exception as e:
        print("Unhandled Error, skipping website..." + url + str(e))
        continue

      
      driver.maximize_window()   
      scheight = 0
      i=0
      while scheight <= 1:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight*%s);" % scheight)
        scheight += .33
        print("Schreibe URL: " + url + " Nummer: " + str(i))
        directory = 'C:\\Users\\Philipp.Meier\\Nextcloud\\Websites\\%s' %(url)
        if not os.path.exists(directory):
          os.makedirs(directory)
        driver.save_screenshot('C:\\Users\\Philipp.Meier\\Nextcloud\\Websites\\%s\\bild%d.png' %(url,i))
        i+=1
        
    driver.quit()

capture()

from selenium import webdriver
import pandas as pd 
import urllib.request
import os
from io import BytesIO
from PIL import Image
 
  
def readCsv():
  data = pd.read_csv("C:/Users/Philipp.Meier/Nextcloud/DeeptechAI/data/urls.csv", sep = ";", encoding = "ISO-8859-1")
  return data

def getListOfURLs(csvData):
  urlList = list()
  for url in csvData.Domain:
    urlList.append(url)
  return urlList

def capture2():

    #options = Options()
    #options.add_argument('-headless')
    driver = webdriver.Firefox(executable_path = 'C:\\Users\\Philipp.Meier\\Nextcloud\\geckodriver.exe')
    driver.maximize_window()
    
    verbose = 0

    urlList = getListOfURLs(readCsv())
    for i in range(3634, len(urlList)): 
      url = urlList[i]
      print("TRYING " + str(i))
      try:
        driver.get('https://' + url)
      except urllib.error.URLError as e:
        print("# URLError: Switching to http")
        try: 
          driver.get('http://' + url)
        except Exception as e:
          print("HTTP and HTTPS call not possible, skipping website..." + url + str(e))
          continue
      except Exception as e:
        print("Unhandled Error, skipping website..." + url + str(e))
        continue

      
      js = 'return Math.max( document.body.scrollHeight, document.body.offsetHeight,  document.documentElement.clientHeight,  document.documentElement.scrollHeight,  document.documentElement.offsetHeight);'

      scrollheight = driver.execute_script(js)
      if verbose > 0:
          print(scrollheight)

      slices = []
      offset = 0
      offset_arr=[]

      while offset < scrollheight:
          if verbose > 0: 
              print(offset)

          #scroll page
          if (scrollheight-offset)<offset:
              driver.execute_script("window.scrollTo(0, %s);" % (scrollheight-offset))
              offset_arr.append(scrollheight-offset)
          else:
              driver.execute_script("window.scrollTo(0, %s);" % offset)
              offset_arr.append(offset)

          try:  
            img = Image.open(BytesIO(driver.get_screenshot_as_png()))
          except Exception as e:
            continue

          offset += img.size[1]
     
          slices.append(img)

          if verbose > 0:
              driver.get_screenshot_as_file('screen_%s.jpg' % (offset))
              print(scrollheight)

      #take screenshot
      screenshot = Image.new('RGB', (slices[0].size[0], scrollheight))
      offset = 0
      offset2= 0
      for img in slices:
          screenshot.paste(img, (0, offset_arr[offset2])) 
          offset += img.size[1]
          offset2+= 1      

      directory = 'C:\\Users\\Philipp.Meier\\Nextcloud\\Websites\\%s' % url
      if not os.path.exists(directory):
        os.makedirs(directory)
      screenshot.save('C:\\Users\\Philipp.Meier\\Nextcloud\\Websites\\%s\\ganzeBild.png' % url)
        
    driver.quit()

capture2()